echo ""
echo "Running Setup..."
echo "[!] Updating package lists"
echo ""
echo "[+] adding dependency 'g++'"
apt-get install g++
echo "[!] g++ is installed"
echo ""
echo "[+] adding dependency 'libcrypto++-dev'"
apt-get install libcrypto++-dev
echo "[!] libcrypto++-dev is installed"
echo ""
echo "[!] Setup complete!"
echo "Run '$ source build.sh' to compile"
echo ""
